import jwt from "jsonwebtoken";

export const verifyToken = (req, res, next) => {
  // this token is generated by postman's cookies after a user has been logged in
  const token = req.cookies.accessToken;
  //console.log(token);

  // the JWT_SECRET_KEY can be generated by us, and while sending request in postman the same code must be send as a token (bearer token in auth)
  if (!token) {
    return res
      .status(401)
      .json({ success: false, message: "You are not authorize!" });
  }

  // if token is exist then verify the token
  jwt.verify(token, process.env.JWT_SECRET_KEY, (err, user) => {
    if (err) {
      return res
        .status(401)
        .json({ success: false, message: "Token is invalid" });
    }

    req.user = user;
    next();
  });
};

// checking whether a user or not
export const verifyUser = (req, res, next) => {
  verifyToken(req, res, next, () => {
    if (req.user.id === req.params.id || req.user.role === "admin") {
      next();
    } else {
      return res
        .status(401)
        .json({ success: false, message: "You are not authenticated" });
    }
  });
};

// checking whether admin or not
export const verifyAdmin = (req, res, next) => {
  verifyToken(req, res, next, () => {
    if (req.user.role === "admin") {
      next();
    } else {
      return res
        .status(401)
        .json({ success: false, message: "You are not authorize" });
    }
  });
};
